blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/your-server-id
    about: Join our Discord server for quick help and theme discussions
  - name: Documentation
    url: https://github.com/yourusername/betterdiscord-theme-template/wiki
    about: Check out our documentation for theme customization guides
